- name: Variable
  hosts: WEB
  vars:
    URL: play.google.com
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
## Ansible access variable with two flower brackets
    - name: Print task variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.google.com